"use client"
import { Provider } from 'react-redux'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import './globals.css'
import store from './store'


const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='container mx-auto text-center py-10 space-x-12'>
            <Link className='' href='/'>Homepage</Link>
            <Link className='' href='/users'>Users</Link>
            <Link className='' href='/create'>Create User</Link>
        </header>
        <Provider store= {store}>
        {children}
        </Provider>
        
        </body>
    </html>
  )
}
